/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PaymentsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePaymentsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePaymentsList.onFilterBar().iCheckFilterField("paymentID");
            Then.onThePaymentsList.onFilterBar().iCheckFilterField("invoiceID");
            Then.onThePaymentsList.onFilterBar().iCheckFilterField("paymentMode");
            Then.onThePaymentsList.onFilterBar().iCheckFilterField("paymentStatus");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onThePaymentsList.onTable().iCheckColumns(6, {"paymentID":{"header":"Payment ID"},"invoiceID":{"header":"Invoice ID"},"amountPaid":{"header":"Amount Paid"},"paymentDate":{"header":"Payment Date"},"paymentMode":{"header":"Payment Mode"},"paymentStatus":{"header":"Payment Status"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onThePaymentsList.onFilterBar().iExecuteSearch();
            
            Then.onThePaymentsList.onTable().iCheckRows();

            When.onThePaymentsList.onTable().iPressRow(0);
            Then.onThePaymentsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});