/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ApprovalsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheApprovalsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheApprovalsList.onFilterBar().iCheckFilterField("approvalID");
            Then.onTheApprovalsList.onFilterBar().iCheckFilterField("orderID");
            Then.onTheApprovalsList.onFilterBar().iCheckFilterField("decision");
            Then.onTheApprovalsList.onFilterBar().iCheckFilterField("approvedBy");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheApprovalsList.onTable().iCheckColumns(6, {"approvalID":{"header":"Approval ID"},"orderID":{"header":"Order ID"},"decision":{"header":"Decision"},"remarks":{"header":"Remarks"},"approvedBy":{"header":"Approved By"},"approvedOn":{"header":"Approved On"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheApprovalsList.onFilterBar().iExecuteSearch();
            
            Then.onTheApprovalsList.onTable().iCheckRows();

            When.onTheApprovalsList.onTable().iPressRow(0);
            Then.onTheApprovalsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});