/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("OrderItemsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheOrderItemsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheOrderItemsList.onFilterBar().iCheckFilterField("itemID");
            Then.onTheOrderItemsList.onFilterBar().iCheckFilterField("orderID");
            Then.onTheOrderItemsList.onFilterBar().iCheckFilterField("productID");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheOrderItemsList.onTable().iCheckColumns(6, {"itemID":{"header":"Item ID"},"orderID":{"header":"Order ID"},"productID":{"header":"Product ID"},"quantity":{"header":"Quantity"},"unitPrice":{"header":"Unit Price"},"itemTotal":{"header":"Item Total"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheOrderItemsList.onFilterBar().iExecuteSearch();
            
            Then.onTheOrderItemsList.onTable().iCheckRows();

            When.onTheOrderItemsList.onTable().iPressRow(0);
            Then.onTheOrderItemsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});