/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CustomersListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheCustomersList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheCustomersList.onFilterBar().iCheckFilterField("customerID");
            Then.onTheCustomersList.onFilterBar().iCheckFilterField("customerName");
            Then.onTheCustomersList.onFilterBar().iCheckFilterField("email");
            Then.onTheCustomersList.onFilterBar().iCheckFilterField("status");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheCustomersList.onTable().iCheckColumns(7, {"customerID":{"header":"Customer ID"},"customerName":{"header":"Customer Name"},"email":{"header":"Email"},"phone":{"header":"Phone"},"creditLimit":{"header":"Credit Limit"},"usedCredit":{"header":"Used Credit"},"status":{"header":"Status"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheCustomersList.onFilterBar().iExecuteSearch();
            
            Then.onTheCustomersList.onTable().iCheckRows();

            When.onTheCustomersList.onTable().iPressRow(0);
            Then.onTheCustomersObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});